### ISSUE TITLE
Use a different user for Gitamic commits

### ISSUE THREAD

**Issue by duncanmcclean** [simonhamp/Gitamic#3]
**Is your feature request related to a problem? Please describe.**
With Statamic's built-in Git integration, it allows you to configure a different Git user for the commits to go through. 

This is helpful as you can then stop a deploy on Forge if the commit was authored by a certain email, which is good as you might not want to deploy what you already have on the server.

**Describe the solution you'd like**
Maybe Gitamic could have a config file with options like this?

```php
'user' => [
  'name' => 'Gitamic',
  'email' => 'gitamic@duncanm.dev',
],
```

Then in my Forge deployment script, I could do:

```
# Cancel deployment if authored by Gitamic
[[ "$FORGE_DEPLOY_AUTHOR" == "SGitamicock" ]] && echo "Commit by $FORGE_DEPLOY_AUTHOR" && exit 0
```

**Describe alternatives you've considered**
I've not really considered any alternatives..

**Additional context**
It's a pretty handy feature for Forge sites as the site doesn't need to go through the whole deployment process, which depending on the site could make the site slow (say you've got lots of content and you have static caching enabled, during deployment you may clear that static cache which could lead to the site being a bit slow until people crawl through the site)

**Are you a Gitamic license holder? Would you pay to have this feature expedited?**
I am, yes!

**Comment by simonhamp** [comment]
@duncanmcclean just release [v1.3](https://github.com/simonhamp/Gitamic/releases/tag/v1.3.0) with some of this support baked in. Fancy giving it a go?

**Comment by duncanmcclean** [comment]
Thanks!

Looks like it kinda works. Although, it seems to have me as the co-commiter... `duncanmcclean authored and Gitamic committed 1 minute ago`

I'm not sure if that's how you intended to implement it?

**Comment by simonhamp** [comment]
Hmmm... interesting. Are you able to use this as a filter on your auto-deployment script?

**Comment by duncanmcclean** [comment]
Hmm, doesn't look like it, here's what I'm adding to my deploy script:

```
# Cancel deployment if authored by Gitamic
[[ "$FORGE_DEPLOY_AUTHOR" == "Gitamic" ]] && echo "Commit by $FORGE_DEPLOY_AUTHOR" && exit 0
```

**Comment by duncanmcclean** [comment]
Looks like the [committer and author](https://github.com/gitonomy/gitlib/blob/1.2/doc/commit.md#author--committer-informations) are different things (from looking at Gitonomy, the package you're using for Git) 🤔 .

**Comment by simonhamp** [comment]
Yeh... I went with committer as it seemed appropriate. The author will be coming from your git config. I guess Forge can't see the difference.

Can you output the `$FORGE_DEPLOY_AUTHOR` without the `if` statement to see which one Forge is picking up?

**Comment by simonhamp** [comment]
(For reference, this is [a git thing](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables#_committing))

**Comment by duncanmcclean** [comment]
`$FORGE_DEPLOY_AUTHOR` outputs `Duncan McClean`

**Comment by duncanmcclean** [comment]
For reference, here's [what's available to me](https://forge.laravel.com/docs/1.0/sites/deployments.html#environment-variables) in my deployment script.

**Comment by simonhamp** [comment]
Ok after playing around with a few variations, it actually seems to make the most sense for these values to be set to the same thing for now (See https://github.com/simonhamp/Gitamic/commit/47a1bad1559d1ea7b046c789a557cf8f0c0452c8, release as v1.3.1).

I'd be interested to see if anyone actually has a use-case for them to be different. Let me know if that looks tidier from your point of view.

**Comment by duncanmcclean** [comment]
Thanks! I'll give it a go tomorrow and let you know how it goes.

**Comment by duncanmcclean** [comment]
Perfect, v1.3.1 does just the job! Appreciate the update, thanks!

**Comment by simonhamp** [comment]
Great news! Thanks for the great feature request and helping to test it @duncanmcclean

**Comment by duncanmcclean** [comment]
No problem!
