### ISSUE TITLE
Pulling possible?

### ISSUE THREAD

**Issue by globalexport** [simonhamp/Gitamic#4]
Hi, 

Does this addon work strictly one-directional or is it possible to optionally pull from repo beforehand?

**Comment by simonhamp** [comment]
At the moment, there's no facility to `pull`. I'm happy to add this and it makes sense for that to exist in the Basic version, but it's worth noting that this can get complex fast depending on your environment and the way that changes are made to your repository.

Merge issues are a potential problem there and resolving those is going to be challenging without any UI to do it. Adding conflict resolution feels very much a Pro feature.

**Comment by globalexport** [comment]
Thanks for your quick response. 
You are right, it would be necessary to diff the changes and to offer new actions on how to resolve possible merge issues. 
It would be very useful though because I sometimes roll out changes to content in bulk. As there is no indication for an editor that the branch has moved ahead, Statamic's own git solution becomes unable to push from the Control Panel. From my experience, this can lead to loss of newly generated data. 

It would be a neat Pro feature to avoid this by fixing the conflicts on a role restricted level.

**Comment by simonhamp** [comment]
[I've added basic `pull` support today](https://github.com/simonhamp/Gitamic/releases/tag/v1.4.0).

This relies on you knowing when to pull and when to push. I haven't tested all edge cases, so you could definitely end up un uncharted territory where git has you sat in the middle of a manual merge, with conflict tags littering your files.

Without the ability to diff, this is really quite dangerous, so I highly recommend that you use this with caution and only `pull` when you know that your branch can be fast-forwarded (the status blurb at the top of the page should help indicate this).

Please let me know how you get on.
