### ISSUE TITLE
Gitamic not loading unstated changes

### ISSUE THREAD

**Issue by mattmultiplied** [simonhamp/Gitamic#42]
**Describe the bug**
Unstaged changes not being fetched by Gitamic, looking at the network request the error is a 500 error on the endpoint of https://www.{domainname.co.uk}/cp/gitamic/api/unstaged

This occurs on the production server but not the staging server which is a carbon copy?

**To Reproduce**
1. Go to Gitamic
2. Click on Refresh OR Load the page

**Expected behavior**
It loads the staged changes.

**Screenshots**

**Versions:**
Statamic 3.3.39 Pro
Laravel 8.83.24
PHP 8.1.12
doublethreedigital/duplicator 2.3.2
edalzell/forma 1.2
simonhamp/gitamic 1.8.4
spatie/statamic-responsive-images 2.14.0
withcandour/aardvark-seo 2.0.28

**Additional context**

**Comment by simonhamp** [comment]
Hey @mattmultiplied, a 500 error should result in something useful being logged to a Laravel log file. Could you dig this out and report back exactly what that error is?

Alternatively, could you [book some time with me](https://calendly.com/simonhamp/chat) (don't worry, it's free) so we can go through this together on a screen share?

**Comment by mattmultiplied** [comment]
Hey Simon,

Apologies for taking a while to reply - I couldn't see anything of any use
in the logs.

I managed to fix it by SSH'ing into the server and manually staging the
changes and is all working now after a new deployment.

Kind Regards

*Matt Wheeler*
-
Mobile: +44(0) 7972 393 231
Email: ***@***.*** / ***@***.***
Website: madeby.studio / mattmultiplied.com

Google Partner  |  Digital Enterprise Top 100  |  Great British
Entrepreneur Awards Finalist  |  Santander X Entrepreneurship Awards Nominee
|  Leeds Digital Festival Thrive Award Nominee  |  Santander X Global
Awards 2021 UK Finalist  |  Yorkshire 42 Under 42 2022

The information in this e-mail (which includes any files transmitted with
it) is confidential and may also be legally privileged. It is intended for
the addressee only. Access to this e-mail by anyone else is unauthorised.
It is not to be relied upon by any person other than the addressee except
with our prior written approval. If no such approval is given, we will not
accept any liability (in negligence or otherwise) arising from any third
party acting, or refraining from acting, on such information. Unauthorised
recipients are required to maintain confidentiality. If you have received
this e-mail in error please notify us immediately, destroy any copies and
delete it from your computer system. Any use, dissemination, forwarding,
printing or copying of this e-mail is prohibited. Copyright in this e-mail
and any document created by me will be and remain vested in us and will not
be transferred to you. We assert the right to be identified as the author
of and to object to any misuses of the contents of this e-mail or such
document

**Comment by simonhamp** [comment]
Glad to hear that. I'll keep my eye out for similar issues, but closing this now that it sounds like it's all working as expected
