### ISSUE TITLE
Can't create a working copy on a bare repository - Error on Fresh Install

### ISSUE THREAD

**Issue by Edbtvplays** [simonhamp/Gitamic#6]
**Describe the bug**
When I installed Gitamic, I then visited the Gitamic Page on my Statamic side bar. I then receive the error
Can't create a working copy on a bare repository

**To Reproduce**
1. Install Gitamic Using Composer. 
2. Follow the install instructions, setting git username and password. Aswell as setting to basic.
3. Visit the cp/gitamic/status or use the link in the sidebar of the CP.
4. See Error.

**Expected behavior**
Gitamic is meant to work, I'm not actually sure what the page is meant to look like.

**Screenshots**
http://i.edbrook.site/brave_vYyLrG8bTU.png

**Versions:**
 - PHP: 8.0.3
 - Browser  [e.g. chrome 87, safari]: Brave Browser
 - Statamic: 3.1.4
 - Gitamic release [e.g. v1.0.0]: v1.5.0
 - Gitamic version [e.g. basic, pro]: Basic

**Additional context**
Add any other context you think may be relevant here.
No Additional Context

**Comment by simonhamp** [comment]
Thanks for reporting this @Edbtvplays.

I'll provide a fix for this soon. In the meantime, you'll need to make an initial commit to your repo to allow Gitamic to get to work.

You should be able to do this using git at the Terminal/Command Prompt:

```
echo "# My project" > README.md
git add README.md
git commit -m "Init"
```

Once that's done, Gitamic should be able to work.

Please let me know how you get on with that.
